export const ADD_SONG = "ADD_SONG";
export const LOAD_SONGS_PAGE_SUCCESS = "LOAD_SONGS_PAGE_SUCCESS";
export const DELETE_SONG_SUCCESS = "DELETE_SONG_SUCCESS";
export const ADD_SONG_SUCCESS = "ADD_SONG_SUCCESS";
export const UPDATE_SONG_SUCCESS = "UPDATE_SONG_SUCCESS";
export const LOAD_SONG_SUCCESS = "LOAD_SONG_SUCCESS";

export const LOAD_GENRES_PAGE_SUCCESS = "LOAD_GENRES_PAGE_SUCCESS";
export const DELETE_GENRE_SUCCESS = "DELETE_GENRE_SUCCESS";
export const ADD_GENRE_SUCCESS = "ADD_Genre_SUCCESS";
export const UPDATE_GENRE_SUCCESS = "UPDATE_Genre_SUCCESS";

export const LOAD_ALBUM_PAGE_SUCCESS = "LOAD_ALBUM_PAGE_SUCCESS";
export const LOAD_ALBUM_DETAILS_SUCCESS = "LOAD_ALBUM_DETAILS_SUCCESS";
export const DELETE_ALBUM_SUCCESS = "DELETE_ALBUM_SUCCESS";
export const ADD_ALBUM_SUCCESS = "ADD_ALBUM_SUCCESS";
export const UPDATE_ALBUM_SUCCESS = "UPDATE_ALBUM_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
