export const ADD_SONG = "ADD_SONG";
export const LOAD_SONGS_PAGE_SUCCESS = "LOAD_SONGS_PAGE_SUCCESS";
export const DELETE_SONG_SUCCESS = "DELETE_SONG_SUCCESS";

export const LOAD_GENRES_PAGE_SUCCESS = "LOAD_GENRES_PAGE_SUCCESS";
export const DELETE_GENRE_SUCCESS = "DELETE_GENRE_SUCCESS";

export const LOAD_ALBUM_PAGE_SUCCESS = "LOAD_ALBUM_PAGE_SUCCESS";
export const LOAD_ALBUM_DETAILS_SUCCESS = "LOAD_ALBUM_DETAILS_SUCCESS";
export const DELETE_ALBUM_SUCCESS = "DELETE_ALBUM_SUCCESS";
