export const ADD_SONG = "ADD_SONG";
export const LOAD_SONGS_PAGE_SUCCESS = "LOAD_SONGS_PAGE_SUCCESS";
export const LOAD_GENRES_PAGE_SUCCESS = "LOAD_GENRES_PAGE_SUCCESS";
export const LOAD_ALBUM_PAGE_SUCCESS = "LOAD_ALBUM_PAGE_SUCCESS";
